"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.POSTGRES_URL = exports.PORT = exports.DB_PORT = exports.DB_NAME = exports.DB_PASSWORD = exports.DB_USER = exports.DB_HOST = void 0;
exports.DB_HOST = 'ep-lively-leaf-584032-pooler.us-east-1.postgres.vercel-storage.com';
exports.DB_USER = 'default';
exports.DB_PASSWORD = '5zrgipIemjq0';
exports.DB_NAME = 'verceldb';
exports.DB_PORT = 5432;
exports.PORT = process.env.PORT || 5000;
exports.POSTGRES_URL = "postgres://default:5zrgipIemjq0@ep-lively-leaf-584032-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb";
